# Generated by Django 4.1 on 2022-08-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(auto_now=True),
        ),
    ]
