# Generated by Django 4.1 on 2022-09-14 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_consulta_alter_paciente_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='cpf',
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
            preserve_default=False,
        ),
    ]
